language: ruby
rvm:
  - 2.2.3
env:
  - DB=postgresql
before_script:
  - psql -c "CREATE USER vekka WITH PASSWORD 'prosiak098';" -U postgres
  - psql -c 'create database refunds_test;' -U postgres

script:
   - RAILS_ENV=test bundle exec rake db:create --trace
   - RAILS_ENV=test bundle exec rake db:migrate --trace
   - bundle exec rake test 
