language: ruby
rvm:
  - 2.2.3
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test

before_script:
  - psql -c "CREATE USER vekka WITH PASSWORD 'prosiak098';" -U postgres
  - psql -c 'create database refunds_test;' -U postgres
